import '../../../../data/models/message_model.dart';

final dummyChat = [
  MessageModel(
    id: '1',
    chatId: 'chat_001',
    senderId: 'user1',
    senderName: 'Faith',
    text: 'Salut 👋',
    sentAt: DateTime.now().subtract(const Duration(minutes: 5)),
    status: MessageStatus.seen,
  ),
  MessageModel(
    id: '2',
    chatId: 'chat_001',
    senderId: 'user2',
    senderName: 'Toi',
    text: 'Hey Faith ! Ça va ?',
    sentAt: DateTime.now().subtract(const Duration(minutes: 4)),
    status: MessageStatus.delivered,
  ),
  MessageModel(
    id: '2',
    chatId: 'chat_001',
    senderId: 'user1',
    senderName: 'Faith',
    text: 'Oui et toi ? 😊',
    sentAt: DateTime.now().subtract(const Duration(minutes: 3)),
    status: MessageStatus.seen,
    isForwarded: true,
  ),
  MessageModel(
    id: '3',
    chatId: 'chat_001',
    senderId: 'user1',
    senderName: 'Faith',
    text: "Besoin d'information 😊",
    sentAt: DateTime.now().subtract(const Duration(minutes: 3)),
    status: MessageStatus.seen,
    isForwarded: false,
  ),
  MessageModel(
    id: '4',
    chatId: 'chat_001',
    senderId: 'user2',
    senderName: 'Toi',
    text: 'Regarde ce fichier',
    fileName: 'rapport.pdf',
    fileUrl: 'files/rapport.pdf',
    replyTo: '3',
    sentAt: DateTime.now().subtract(const Duration(minutes: 2)),
    status: MessageStatus.seen,
  ),
  MessageModel(
    id: '5',
    chatId: 'chat_001',
    senderId: 'user1',
    senderName: 'Faith',
    text: 'Merci 🙏',
    replyTo: '4',
    sentAt: DateTime.now().subtract(const Duration(minutes: 1)),
    status: MessageStatus.seen,
  ),
];
